name: "CI/CD for my try"
on: workflow_dispatch

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: "setup node.js"
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
            - name: "checkout"
              uses: actions/checkout@v4
            - name: "install dependencies"
              run: npm install
            - name: "install pm2"
              run: npm install pm2 -g
           
            - name: "start server"
              run: pm2 start src/App.js